### ISSUE TITLE
Question about parameter 'cluster_row'

### ISSUE THREAD

**Issue by Rong-ao** [junjunlab/JunJunZai#1]
Hi JunJun!
I am trying to use your package JunJunZai to visualization my results from HOMER.
It is an excellent package! But I am not sure about what parameter "cluster_rows" means in the function "plotMotifHeatmap()".
Thanks for your contribution again!

**Comment by junjunlab** [comment]
**cluster_rows** means whether cluster rows for the heatmap according to the ajusted pvalue. If you set **clustForMotif == TRUE**, this parameter will be changed according to motif similarity.
