### ISSUE TITLE
Color in heatmap

### ISSUE THREAD

**Issue by Rong-ao** [junjunlab/JunJunZai#2]
Hi JunJun!
In output heatmap of your package, I found the color of "bgPer" and "tgPer" bars are randomly chosen.
What are the meaning of these 2 values? And how should I do if I want to keep these color consistant (not randomly changed) at each time I draw the plot?

**Comment by junjunlab** [comment]
**tgPer** means **percentage of Targets Sequences with Motif**, **bgPer** means **percentage  of Background Sequences with Motif**. You can use **set.seed()** function before plotting heatmap to keep the color consistant.

**Comment by Rong-ao** [comment]
Thanks! It helped me a lot! :）
